name: Deploy

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy the Docker image
        run: |
          tag=ghcr.io/johannesbyle/turbotin:$(date +%s)

          docker build . --file Dockerfile --tag $tag
          docker push $tag

          mkdir ~/.ssh/
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan "${{ secrets.LINODE_IP }}" > ~/.ssh/known_hosts
          ssh root@${{ secrets.LINODE_IP }} ". deploy.sh $tag" > /dev/null
